spring:
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://products-db:5432/postgres
    username: postgres
    password: postgres
