server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    default-schema: products
    schemas: products
    create-schemas: true
    table: flyway_schema_history_products
products:
  security:
    header: X-API-KEY
    expectedKey: ${PRODUCTS_API_KEY:products-secret}
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
logging:
  structured:
    format:
      console: ecs
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

---
server:
  port: 8080
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
