services:
  products-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: acme/products-service:latest
    container_name: products-app
    depends_on:
      products-db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://products-db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"

  products-db:
    image: postgres:15-alpine
    container_name: products-postgres
    environment:      
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 20s
      retries: 5
    ports:
      - "5433:5432"
    volumes:
      - pgdata_products:/var/lib/postgresql/data

volumes:
  pgdata_products:
