services:
  db:
    image: postgres:15-alpine
    container_name: products-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 5s
      timeout: 20s
      retries: 5
    volumes:
      - db:/var/lib/postgresql/data

  app:
    build:
      context: .
    image: acme/products-service:latest
    container_name: products-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB:-postgres}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PRODUCTS_API_KEY: ${PRODUCTS_API_KEY:-products-secret}
      SERVER_PORT: 8080
    ports:
      - "8080:8080"

volumes:
  db:
